

// export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
// export const CLEAR_PRODUCT= 'CLEAR_PRODUCT';
export const GET_METRICAS_SUCCESS= 'GET_METRICAS_SUCCESS';
export const GET_DEPOT_LIST_SUCCESS= 'GET_DEPOT_LIST_SUCCESS';

